import {StyleSheet} from 'react-native';
import {Fonts, Sizes} from '../../../../assets/RootStyle';

const styles = () => {
  return StyleSheet.create({
    page: {
      height: '100%',
      position: 'absolute',
      width: '100%',
    },
    close: {
      left: Sizes.size150,
      width: Sizes.size20,
      height: Sizes.size20,
      padding: Sizes.size5,
    },
    time2: {
      left: Sizes.size3,
      marginTop: Sizes.size5,
      width: Sizes.size338,
      height: Sizes.size35,
      padding: Sizes.size5,
      borderWidth: Sizes.size1,
      borderColor: '#347474',
      borderRadius: Sizes.size4,
      justifyContent: 'center',
      alignItems: 'center',
    },
    flat: {
      width: Sizes.size342,
      marginTop: Sizes.size24,
    },
    time: {
      width: Sizes.size115,
      height: Sizes.size32,
      padding: Sizes.size5,
      borderWidth: Sizes.size1,
      borderColor: '#347474',
      borderRadius: Sizes.size4,
      marginVertical: Sizes.size5,
      marginRight: Sizes.size60,
      justifyContent: 'center',
      alignItems: 'center',
    },
    time1: {
      width: Sizes.size105,
      height: Sizes.size35,
      padding: Sizes.size5,
      borderWidth: Sizes.size1,
      backgroundColor: '#347474',
      borderRadius: Sizes.size4,
      margin: Sizes.size5,
      justifyContent: 'center',
      alignItems: 'center',
    },
    container: {
      flex: 1,
      padding: Sizes.size24,
      backgroundColor: 'rgba(52, 52, 52, 0.8)',
    },
    container2: {
      width: Sizes.size288,
      marginTop: Sizes.size20,
    },
    content: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    touchable: {
      marginTop: Sizes.size50,
      width: Sizes.size287,
      height: Sizes.size38,
      backgroundColor: '#11493E',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: Sizes.size4,
    },
    timeTouch: {
      height: Sizes.size38,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#347474',
    },
    jam: {
      color: '#FCFCFC',
      marginHorizontal: Sizes.size95,
    },
    input: {
      fontFamily: Fonts.regular,
      color: '#818195',
      marginLeft: Sizes.size10,
      padding: Sizes.size5,
    },
    desc: {
      alignItems: 'flex-start',
      borderRadius: Sizes.size6,
      marginTop: Sizes.size20,
      width: Sizes.size288,
      height: Sizes.size90,
      borderWidth: Sizes.size1,
      borderColor: '#E3E3E3',
    },
    text1: {
      fontFamily: Fonts.bold,
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: Sizes.size16,
      lineHeight: Sizes.size24,
      letterSpacing: 0.25,
      color: '#11493E',
      alignSelf: 'flex-start',
      marginLeft: Sizes.size40,
    },
    text2: {
      fontFamily: Fonts.regular,
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: Sizes.size16,
      lineHeight: Sizes.size24,
      letterSpacing: 0.25,
      color: '#616062',
      alignSelf: 'flex-start',
      marginLeft: Sizes.size40,
      marginTop: Sizes.size24,
    },
    textFlat: {
      fontFamily: Fonts.regular,
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: Sizes.size14,
      lineHeight: Sizes.size16,
      letterSpacing: 0.25,
      color: '#949494',
    },
    text: {
      fontFamily: Fonts.regular,
      color: '#FCFCFC',
      fontSize: Sizes.size14,
    },
  });
};

export {styles};
